'use client'

import { useState } from 'react'
import { ChevronDown, CircleHelp, LogOut, Menu, Navigation, Settings, X } from 'lucide-react'

export function Sidebar() {
  const [open, setOpen] = useState(false)
  return <><button aria-label="Open navigation" onClick={() => setOpen(true)} className="fixed left-4 top-4 z-40 rounded-md border border-border bg-panel p-2 text-muted-foreground lg:hidden"><Menu size={18} /></button><aside className={`fixed inset-y-0 left-0 z-30 flex w-60 flex-col border-r border-border bg-sidebar transition-transform duration-200 lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-16 items-center justify-between border-b border-border px-5"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-md bg-foreground text-background"><Navigation size={15} fill="currentColor" /></span><div><div className="text-[11px] font-bold tracking-[0.2em] text-foreground">AERODYNE</div><div className="text-[8px] uppercase tracking-[0.24em] text-muted-foreground">Flight systems</div></div></div><button aria-label="Close navigation" onClick={() => setOpen(false)} className="text-muted-foreground lg:hidden"><X size={17} /></button></div><div className="border-b border-border p-4"><button className="flex w-full items-center justify-between rounded-md bg-panel px-3 py-2.5 text-left"><span><span className="block text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Active fleet</span><span className="text-xs font-medium">Pacific Operations</span></span><ChevronDown size={15} className="text-muted-foreground" /></button></div><nav className="flex-1 p-3" aria-label="Main navigation"><p className="px-3 pb-2 pt-1 text-[9px] uppercase tracking-[0.18em] text-muted-foreground">Operations</p><button aria-current="page" className="flex w-full items-center gap-3 rounded-md bg-foreground/10 px-3 py-2.5 text-left text-xs text-foreground"><Navigation size={16} /><span>Live flights</span></button><button className="mt-3 flex w-full items-center justify-center rounded-md bg-foreground px-3 py-2.5 text-xs font-medium text-background transition-colors hover:bg-foreground/80" onClick={() => window.dispatchEvent(new Event('new-mission'))}>+ Add mission</button></nav><div className="space-y-1 border-t border-border p-3"><button className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-xs text-muted-foreground hover:bg-panel hover:text-foreground"><Settings size={16} />Settings</button><button className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-xs text-muted-foreground hover:bg-panel hover:text-foreground"><CircleHelp size={16} />Operator help</button><button className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-xs text-muted-foreground hover:bg-panel hover:text-foreground"><LogOut size={16} />Sign out</button></div></aside>{open && <button aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-black/60 lg:hidden" onClick={() => setOpen(false)} />}</>
}
