apiVersion: v1
kind: Service
metadata:
  name: vera-app
  namespace: vella-fleet
  labels:
    app.kubernetes.io/name: vera-app
    app.kubernetes.io/component: dashboard-frontend
    app.kubernetes.io/part-of: vera-delivery-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: vera-app
