name: Kubernetes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.31.0

      - name: Validate Development
        run: kubectl kustomize ./k8s/overlays/dev

      - name: Validate Production
        run: kubectl kustomize ./k8s/overlays/prod
